### ISSUE TITLE
seems like rake tolk:sync isn't working on rails 3.2.17

### ISSUE THREAD

**Issue by giedriusr** [tolk/tolk#60]
Environment:
rails: 3.2.17
Gemfile:
gem 'tolk'
// gem "protected_attributes" is not included due to error message:

```
Resolving dependencies...
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    protected_attributes (>= 0) ruby depends on
      activemodel (< 5.0, >= 4.0.0.beta) ruby

    active_attr (>= 0) ruby depends on
      activemodel (3.2.17)
```

When not using it, bundle works fine, migrations as well. But sync isn't.

```
rake aborted!
undefined method `each' for nil:NilClass
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/gems/tolk-1.3.12/lib/tolk/sync.rb:24:in `flat_hash'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/gems/tolk-1.3.12/lib/tolk/sync.rb:20:in `read_primary_locale_file'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/gems/tolk-1.3.12/lib/tolk/sync.rb:15:in `load_translations'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/gems/tolk-1.3.12/lib/tolk/sync.rb:9:in `sync!'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/gems/tolk-1.3.12/lib/tasks/tolk_tasks.rake:19:in `block (2 levels) in <top (required)>'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/gems/tolk-1.3.12/lib/tasks/tolk_tasks.rake:13:in `block (2 levels) in <top (required)>'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/giedrius/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => tolk:sync
```

Anyone else has same issue?
